#!/bin/bash

# See https://github.com/adriancooney/Taskfile for the inspiration

DEFAULT_REPO="mmocg"

if [ -z "$(git status --porcelain)" ]; then 
  DEFAULT_TAG=$(cat ./VERSION 2>/dev/null)
else 
  DEFAULT_TAG="dev"
fi

function help {
    echo "I'm a Taskfile codifying tasks needed to work with this here code."
    echo "$0 <task> <args>"
    echo "Available tasks:"
    grep function $0 | cut -d' ' -f2 | xargs printf "\t%s\n"
}

function build {
    go build
}

function startdb {
    docker run -d --name mmocg-db -p5432:5432 -e POSTGRES_PASSWORD=hunter2 postgres
    echo export DATABASE_URL=postgres://postgres:hunter2@localhost:5432/postgres
}

function start {
    build # this is a thing Make handles better ...
    ./mmocg -allow-origin 'http://localhost:*'
}

function dockerbuild {
    image="$DEFAULT_REPO"
    tag="$DEFAULT_TAG"
    if [ -n "$1" ]; then
        image="$1"
    fi
    if [ -n "$2" ]; then
        tag="$2"
    fi
    go mod tidy
    docker build -t "$image:$tag" .
}

function dockerpush {
    image="$DEFAULT_REPO"
    tag="$DEFAULT_TAG"
    if [ -n "$1" ]; then
        image="$1"
    fi
    if [ -n "$2" ]; then
        tag="$2"
    fi
    docker push "$image:$tag"
}

function swagger-editor {
    docker run -d -p 8080:8080 swaggerapi/swagger-editor
    echo Open http://localhost:8080 in your browser to use the Swagger editor.
    echo Use File ">" Import file to load the yaml you want to edit.
}

function todo {
    sources=$(find . -name '*go')
    todo_pattern='.*TODO (.*)'
    output_pattern='- [ ] \1: \2'
    grep TODO $sources | sed -E 's_\./(.*):'"$todo_pattern"'_'"$output_pattern"'_' | sort -u | tr '\t' ' ' | tr -s ' '
}

TIMEFORMAT="Task completed in %3lR"

time ${@:-help}
